### ISSUE TITLE
Do not overwrite default failure transport

### ISSUE THREAD

**Issue by morgannilsson** [pimcore/generic-data-index-bundle#238]
generic-data-index-bundle/config/pimcore/messenger.yaml
```
framework:
    messenger:
        enabled: true
        failure_transport: pimcore_generic_data_index_failed

```
Should be:

```
framework:
    messenger:
        transports:
            pimcore_generic_data_index:
                dsn: "doctrine://default?queue_name=pimcore_generic_data_index_queue"
                failure_transport: pimcore_generic_data_index_failed
```
